name: Build

on:
  push:
    tags:
      - v*
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.13"
  GTK_ROOT: C:\gtk-build\gtk\x64\release

jobs:
  binaries:
    name: Binary ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
          use-dist: true
          cross: true

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Install GTK4 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y girepository-2.0
      - name: Seed pip
        run: uv venv --seed

      - name: Install the project
        run: |
          uv sync --locked --group release --no-default-groups

      - name: Build binary
        run: |
          uv run scripts/build_binary.py packaging --archive --suffix "${{ matrix.job.target }}"

      - name: Upload staged archive
        if: runner.os != 'Linux'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: staged-${{ runner.os }}-${{ matrix.job.target }}
          path: packaging/*
          if-no-files-found: error

      - name: Upload archive
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: standalone-${{ matrix.job.target }}
          path: packaging/*
          if-no-files-found: error
