name: Build

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    release:
      types:
        - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.13"
  GTK_ROOT: C:\gtk-build\gtk\x64\release

jobs:
  gtk:
    name: Prepare gtk ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            use-dist: true
          - target: i686-pc-windows-msvc
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Seed pip
        run: uv venv --seed

      - name: Cache GTK Build
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: C:\gtk-build
          key: gtk-${{ matrix.job.target }}-${{ github.event.release.tag_name || github.ref_name }}

      - name: Build GTK4
        run: |
          uv run --only-group gtk gvsbuild build --ninja-opts -j2 --enable-gi --py-wheel gtk4 pygobject

      - name: Archive GTK runtime
        run: |
          7z a -tzip GTK4_Gvsbuild-${{ matrix.job.target }}.zip ${env:GTK_ROOT}\*

      - name: Upload GTK4_Gvsbuild-${{ matrix.job.target }}.zip
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: GTK4_Gvsbuild-${{ matrix.job.target }}.zip
          path: GTK4_Gvsbuild-${{ matrix.job.target }}.zip

  binaries:
    name: Binary ${{ matrix.job.target }} (${{ matrix.job.os }})
    needs:
      - gtk
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # Linux
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            use-dist: true
            cross: true
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            use-dist: true
            cross: true
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: powerpc64le-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            use-dist: true
          - target: i686-pc-windows-msvc
            os: windows-latest
          # macOS
          - target: aarch64-apple-darwin
            os: macos-latest
            use-dist: true
          - target: x86_64-apple-darwin
            os: macos-latest
            use-dist: true

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Cache GTK Build
        if: runner.os == 'Windows'
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: C:\gtk-build
          key: gtk-${{ matrix.job.target }}-${{ github.event.release.tag_name || github.ref_name }}
          fail-on-cache-miss: true

      - name: Install GTK4 dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository-2.0-dev

      - name: Seed pip
        run: uv venv --seed

      - name: Install the project
        run: |
          uv sync --locked --group release --no-default-groups

      - name: Prepare the project
        if: runner.os == 'Windows'
        run: |
          $env:PATH = "${env:GTK_ROOT}\bin;" + $env:PATH
          $env:LIB = "${env:GTK_ROOT}\lib;" + $env:LIB
          $env:INCLUDE = "${env:GTK_ROOT}\include;${env:GTK_ROOT}\include\cairo;${env:GTK_ROOT}\include\glib-2.0;${env:GTK_ROOT}\include\gobject-introspection-1.0;${env:GTK_ROOT}\lib\glib-2.0\include;" + $env:INCLUDE
          uv pip install --force-reinstall (Resolve-Path ${env:GTK_ROOT}\wheels\PyGObject*.whl)
          uv pip install --force-reinstall (Resolve-Path ${env:GTK_ROOT}\wheels\pycairo*.whl)

      - name: Build binary
        run: |
          uv run scripts/build_binary.py packaging --archive --suffix "${{ matrix.job.target }}"

      - name: Upload staged archive
        if: runner.os != 'Linux'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: staged-${{ runner.os }}-${{ matrix.job.target }}
          path: packaging/*
          if-no-files-found: error

      - name: Upload archive
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: standalone-${{ matrix.job.target }}
          path: packaging/*
          if-no-files-found: error
